### ISSUE TITLE
Pin mapping for SDCard I/F

### ISSUE THREAD

**Issue by vedecoid** [rzeldent/platformio-espressif32-sunton#24]
I was going through the pin mappings for the SDcard I/F on the  7" and 4" 800x480 displays (ESP32-8048S043-C and ESP32-8048S070-C) and noticed that they do not comply with the schematic for these boards. In the config files, these mappings are used
      "-DTF_CS=5",
      "-DTF_SPI_MOSI=23",
      "-DTF_SPI_SCLK=18",
      "-DTF_SPI_MISO=19"
while the schematic shows:
CS : IO10
MOSI : IO11
CLK : IO12
MISO : IO13

**Comment by rzeldent** [comment]
Thanks! Has been updated!

**Comment by vedecoid** [comment]
:-)
I only checked the 2 boards I own though...

**Comment by rzeldent** [comment]
The schematics are in the repo and checked; all these never boards have this IO assignment!
Thanks again for mentioning.
