### ISSUE TITLE
8048S050C with ST7262 controller : GPIO definitions for RED and BLUE swapped in bord definition file

### ISSUE THREAD

**Issue by axel1202** [rzeldent/platformio-espressif32-sunton#35]
**thanks for the great work putting this together!** :smile:
 
There might be an issue, when using a SUNTON 8048S050C (5", IPS, touch) board. When using the [board definition file](https://github.com/rzeldent/platformio-espressif32-sunton/blob/main/esp32-8048S050C.json) from this repo, red and blue get swapped on the display. I checked with the manufacturer's schematics and that confirms, that this is caused by the GPIO definitions in that board definition file. Swapping the GPIO definitions solves this issue.

This might  well be a SUNTON-specific issue or just an issue with whatever manufacturer produced my particular board. As this is such a minor thing and I can't be sure, that this is not just a manufacturer specific issue, I didn't want to go through cloning and then sending a pull request - so, here are the adjusted definitions:

    "'-D ST7262_PANEL_CONFIG_DATA_GPIO_B0=8'",
    "'-D ST7262_PANEL_CONFIG_DATA_GPIO_B1=3'",
    "'-D ST7262_PANEL_CONFIG_DATA_GPIO_B2=46'",
    "'-D ST7262_PANEL_CONFIG_DATA_GPIO_B3=9'",
    "'-D ST7262_PANEL_CONFIG_DATA_GPIO_B4=1'",
    "'-D ST7262_PANEL_CONFIG_DATA_GPIO_G0=5'",
    "'-D ST7262_PANEL_CONFIG_DATA_GPIO_G1=6'",
    "'-D ST7262_PANEL_CONFIG_DATA_GPIO_G2=7'",
    "'-D ST7262_PANEL_CONFIG_DATA_GPIO_G3=15'",
    "'-D ST7262_PANEL_CONFIG_DATA_GPIO_G4=16'",
    "'-D ST7262_PANEL_CONFIG_DATA_GPIO_G5=4'",
    "'-D ST7262_PANEL_CONFIG_DATA_GPIO_R0=45'",
    "'-D ST7262_PANEL_CONFIG_DATA_GPIO_R1=48'",
    "'-D ST7262_PANEL_CONFIG_DATA_GPIO_R2=47'",
    "'-D ST7262_PANEL_CONFIG_DATA_GPIO_R3=21'",
    "'-D ST7262_PANEL_CONFIG_DATA_GPIO_R4=14'",

Maybe that helps other ppl... Soon I'll get SUNTONS 7" boards and re-visit this issue....

**Comment by rzeldent** [comment]
Hi Axel,

You're right. I changed this yesterday after examining the schematic and saw it was not correct in the definitions. So, the values there were correct, but the schematic is apparently wrong. Will correct this asap...

**Comment by rzeldent** [comment]
esp32-8048S050N was still okay, R and C should be good now!
See https://github.com/rzeldent/platformio-espressif32-sunton/commit/f10c559701433a85fb32944faf05c3bfae5706fe

**Comment by axel1202** [comment]
Nit sure, whether the schematics were wrong - I've got the [schematics from here](http://pan.jczn1688.com/1/ESP32%20module) and they match those corrected definitions - so I guess, that might be manufactruer-dependent :-) Anyway - thanks for the quick reply :-)
