### ISSUE TITLE
not work installation board

### ISSUE THREAD

**Issue by herry93** [rzeldent/platformio-espressif32-sunton#37]
PIO Core Call Error: "The following files/directories have been created in D:\project\esp32-s3 tft\master\ver 2 LVGA\r\ninclude - Put project header files here\r\nlib - Put project specific (private) libraries here\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\nResolving esp32-4827S043C dependencies...\r\n\n\nUnknownBoard: Unkn
![image](https://github.com/rzeldent/platformio-espressif32-sunton/assets/43225911/d6e0006c-ccdb-460e-97d2-f512bed7d62f)
own board ID 'esp32-4827S043C'"

**Comment by rzeldent** [comment]
You need to checkout with submodules. The boards directory will then contain the boards

**Comment by rzeldent** [comment]
Assume this has been resolved...
