### ISSUE TITLE
Screen Flickering 

### ISSUE THREAD

**Issue by gathualex** [rzeldent/platformio-espressif32-sunton#44]
Screen flickers  after building from main and latest release.  Find attached video.

https://github.com/rzeldent/platformio-espressif32-sunton/assets/143402429/7cadb53a-e9b8-4fd1-bef1-a0ba06bd6c72

**Comment by rzeldent** [comment]
Hi Alex,

I do not own the esp32-8042S050C but rely on others.
Check the PCLK and Porch values
