### ISSUE TITLE
Schematic for ESP32-4848S040

### ISSUE THREAD

**Issue by flexiti** [rzeldent/platformio-espressif32-sunton#45]
@rzeldent  Is there a chance for a schematic diagram of this model? :)

**Comment by rzeldent** [comment]
No, not that I know of. I informed if the reseller had a schematic but got a reply that all needed was in the xls file in the project.
I made some closeup pictures and read some comments. Should you find a schematic please let me know so I can include it in the boards!

**Comment by flexiti** [comment]
ok
