### ISSUE TITLE
ESP32-2432S022N - How to access the Battery Interface?

### ISSUE THREAD

**Issue by igasmi** [rzeldent/platformio-espressif32-sunton#64]
I am trying to access the battery voltage in order to calculate my battery percentage, but I don't know which pin it is connected to. Any idea where I can find this information?

**Comment by rzeldent** [comment]
Hi,

There is no battery input pin. The voltage to the Vcc is regulated so should be constant.
I think you'll have to make a circuit yourself and use one of the A/D converters....

**Comment by igasmi** [comment]
Thank you @rzeldent . That's what I've ended up doing. I wish that there was a more elegant solution than that

![37fc0a6f-35f1-4d10-a5de-db15ad5ddf8a](https://github.com/user-attachments/assets/6dffafee-b06a-4c16-b02f-b4c7cb29405c)
